server:
  port: 8600

spring:
  redis:
    database: 1             # Redis数据库索引（默认为0）
    host: 47.107.120.118         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: cardlan        # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 1000
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 2
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0

